#! /usr/bin/env python

import time

# ROS
import rospy
from std_msgs.msg import String

# Firebase
import firebase_admin
from firebase_admin import credentials
from firebase_admin import db

class Listener:
    def __init__(self):
        rospy.init_node('rosFirebase', anonymous=True)
        rospy.Subscriber("ros_to_firebase", String, callback=self.callback)
        self.pub = rospy.Publisher("firebase_to_ros", String, queue_size=10)
        
        self.cred = credentials.Certificate('mca_key.json') # Key Certification

        firebase_admin.initialize_app(self.cred, {
            'databaseURL': 'https://project1-6dfc7-default-rtdb.firebaseio.com/' # Database url
        })
        
        self.talker()

    def callback(self, msg):
        if msg.data == "start":
            data = {'qr' : msg.data}
            ref = db.reference('')
            ref.update(data)
            print("QR.data: " + msg.data)
        
    def talker(self):
        while not rospy.is_shutdown():
            mg1 = db.reference('Magnetic/Magnetic1')
            mg1_data = mg1.get() 
        
            if mg1_data == "1":
                print("Mg1.data: " + mg1_data)
                self.pub.publish(mg1_data)
                time.sleep(1)
                mg1 = db.reference('Magnetic')
                mg1.update({'Magnetic1' : "0"})


if __name__ == '__main__':
    print(
    '''
ROS & Firebase communication
------------------------------
    '''
    )
    l = Listener()
