#!/usr/bin/env python
# -*- coding: utf-8 -*-

import rospy
import math
import subprocess

from std_msgs.msg import String
from nav_msgs.msg import OccupancyGrid
from geometry_msgs.msg import PoseWithCovarianceStamped

class MapLoader:
    def __init__(self):
        self.map_path = ""
        self.map_pub = rospy.Publisher("/initialpose", PoseWithCovarianceStamped, queue_size=10)
        self.map_sub = rospy.Subscriber("/map_change", String, self.map_change_callback)
        rospy.init_node("map_loader")


    def load_map(self):
        subprocess.Popen(["rosrun", "map_server", "map_server", self.map_path])

    def set_initial_pose(self, x, y, z, w):
        initial_pose = PoseWithCovarianceStamped()
        initial_pose.header.frame_id = "map"
        initial_pose.pose.pose.position.x = x
        initial_pose.pose.pose.position.y = y
        initial_pose.pose.pose.orientation.z = z
        initial_pose.pose.pose.orientation.w = w
        initial_pose.pose.covariance[6*0+0] = 0.5 * 0.5
        initial_pose.pose.covariance[6*1+1] = 0.5 * 0.5
        initial_pose.pose.covariance[6*5+5] = (math.pi/12.0) * (math.pi/12.0)
        return initial_pose

    def map_change_callback(self, msg):
        if msg.data == "serving":
            self.map_path = "/home/hyun/project3/src/DMU_3-1_Project/navigation/maps/serving.yaml"
            self.load_map()
            rospy.sleep(0.5)
            pose1 = self.set_initial_pose(-0.790206024071, 0.046478162091, -0.672337570793, 0.740244683128)
            self.map_pub.publish(pose1)
            rospy.loginfo("Setting initial pose to: {}".format(pose1))
            
        elif msg.data == "hotel":
            self.map_path = "/home/hyun/project3/src/DMU_3-1_Project/navigation/maps/hotel.yaml"
            self.load_map()
            rospy.sleep(0.5)
            pose2 = self.set_initial_pose(0.211809694767,-1.1462250948, 0.713927267515, 0.700219863114)
            self.map_pub.publish(pose2)
            rospy.loginfo("Setting initial pose to: {}".format(pose2))
            
        else:
            rospy.logwarn("Invalid map_change message received")

if __name__ == "__main__":
    l = MapLoader()
    rospy.loginfo("[Load map ON]")
    rospy.spin()